### ISSUE TITLE
`latest` image does not start up correctly

### ISSUE THREAD

**Issue by SplinterHead** [fazalfarhan01/EarnApp-Docker#36]
I'm trying to run the `latest` version of the earnapp image so it can create it's own UUID, but it is hitting the following error: 
`Couldn't find an alternative telinit implementation to spawn.`

Looking around, it sounds like it's to do with the `privileged` and `/sys/fs/cgroup` settings, but those are set in my docker compose config

```yaml
version: '3.8'

services:
  earnapp:
    image: fazalfarhan01/earnapp
    container_name: cf_earnapp
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /storage/data/earnapp:/etc/earnapp
    restart: always
```
