### ISSUE TITLE
Invalid node id

### ISSUE THREAD

**Issue by Jeoffreybauvin** [fazalfarhan01/EarnApp-Docker#4]
Hi,

I'm using this compose : 

```
version: "3.3"
services:
    app:
        image: fazalfarhan01/earnapp
        privileged: true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - /home/jeoffrey/data/earnapp/etc:/etc/earnapp
```

And I'm getting the nod id from the file "uuid", but he's invalid : 

sdk-node-9616f4XXXXXXXXXXXXeceb03 : Error while linking device. The device is not found

Any idea ? Anything I can check ?

Regards,
