### ISSUE TITLE
ID is not created?

### ISSUE THREAD

**Issue by N1CK145** [fazalfarhan01/EarnApp-Docker#7]
Hi,
i cant register my device.

```bash
root@raspberrypi: ~/docker/earnapp/etc# docker-compose up -d
                            Starting earnapp_app_1 ... done


root@raspberrypi: docker ps
CONTAINER ID   IMAGE                   COMMAND        CREATED         STATUS              PORTS     NAMES
c4662f07c8d1   fazalfarhan01/earnapp   "/sbin/init"   2 minutes ago   Up About a minute             earnapp_app_1


root@raspberrypi:~/docker/earnapp/etc# docker-compose exec app earnapp status
✔ Current status: disabled


root@raspberrypi:~/docker/earnapp/etc# docker-compose exec app earnapp register
⚠ You must register it for earnings to be added to your account.
⚠ Open the following URL in the browser:
  https://earnapp.com/r/


root@raspberrypi:~/docker/earnapp/etc# docker-compose exec app earnapp showid
(Its empty)
```

docker-compose.yml
```yml
version: "3.3"
services:

    app:
        image: fazalfarhan01/earnapp
        privileged: true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./etc:/etc/earnapp
```

more information

```
root@rapsberrypi: uname -a
Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

Docker: 
Docker version 20.10.12, build e91ed57

Docker-Compose:
docker-compose version 1.21.0, build unknown
```
